// This file is generated by Velite

import config from '../velite.config';

type Collections = typeof config.collections;

export type Blog = Collections['blogs']['schema']['_output'];
export declare const blogs: Blog[];

export type Tags = Collections['tags']['schema']['_output'];
export declare const tags: Tags[];
