import AppHeader from '@/components/common/app-header';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  weight: ['200', '300', '400', '500'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <div className='container flex min-h-screen flex-col lg:px-60'>
          <AppHeader />
          <div className='flex-1'>{children}</div>
        </div>
      </body>
    </html>
  );
}
